name: pdf_svg
description: SVG - Robust rendering of Scalable Vector Graphic images, supporting a well-defined profile of SVG, a fast-loading binary storage format, and animation.
version: 1.1.30
homepage:  https://bill.jovial.com/

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  pdf: ^3.10.4
  xml: ^7.0.1
  collection: ^1.15.0
  args: ^2.0.0
  vector_math: ^2.1.0
  jovial_misc: ^0.10.0
  http: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

executables:
  avd_to_si:
  svg_to_si:

repository: https://github.com/zathras/jovial_svg

issues: https://github.com/zathras/jovial_svg/issues
